# Generated by Django 4.2 on 2023-04-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
        migrations.CreateModel(
            name='ShowCreator',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('imdb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('categories', models.ManyToManyField(related_name='show', related_query_name='shows', to='mttrchrdsapi.showcategory')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show', related_query_name='shows', to='mttrchrdsapi.showcreator')),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
    ]
