# Generated by Django 4.2 on 2023-04-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mttrchrdsapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='showcreator',
            name='image_url',
        ),
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to='shows/'),
        ),
        migrations.AddField(
            model_name='showcreator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shows/creators/'),
        ),
    ]
