# Generated by Django 4.2 on 2023-04-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mttrchrdsapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
