# Generated by Django 4.2 on 2023-04-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mttrchrdsapi', '0002_remove_show_image_url_remove_showcreator_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
        migrations.CreateModel(
            name='GameCreator',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/creators/')),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/platforms/')),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
        migrations.CreateModel(
            name='ShowPlatform',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shows/platforms/')),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('imdb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='games/')),
                ('categories', models.ManyToManyField(related_name='game', related_query_name='games', to='mttrchrdsapi.gamecategory')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', related_query_name='games', to='mttrchrdsapi.gamecreator')),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
    ]
