# Generated by Django 4.2 on 2023-04-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mttrchrdsapi', '0003_gamecategory_gamecreator_gameplatform_showplatform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mttrchrdsapi.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('game_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', related_query_name='activities', to='mttrchrdsapi.game')),
                ('game_platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', related_query_name='activities', to='mttrchrdsapi.gameplatform')),
                ('show_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', related_query_name='activities', to='mttrchrdsapi.show')),
                ('show_platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', related_query_name='activities', to='mttrchrdsapi.showplatform')),
            ],
            bases=('mttrchrdsapi.basemodel',),
        ),
    ]
