# Generated by Django 4.2 on 2023-04-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mttrchrdsapi', '0004_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.AlterField(
            model_name='activity',
            name='game_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', related_query_name='activities', to='mttrchrdsapi.game'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='game_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', related_query_name='activities', to='mttrchrdsapi.gameplatform'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='show_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', related_query_name='activities', to='mttrchrdsapi.show'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='show_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', related_query_name='activities', to='mttrchrdsapi.showplatform'),
        ),
    ]
