# Generated by Django 4.2 on 2023-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mttrchrdsapi', '0005_remove_activity_name_alter_activity_game_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='games/thumbnails/'),
        ),
        migrations.AddField(
            model_name='show',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='shows/thumbnails/'),
        ),
    ]
