# Generated by Django 4.2.10 on 2024-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mttrchrdsapi', '0006_game_thumbnail_show_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='rating',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
